# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svogrig <svogrig@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/16 18:52:57 by svogrig           #+#    #+#              #
#    Updated: 2025/02/20 11:58:23 by svogrig          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:=	unnecessary_violence

SRC		:=	main.cpp \
			HumanA.cpp \
			HumanB.cpp \
			Weapon.cpp

include ../ex00/Makefile
